version: '3.4'
name: microservice-ecommerce
networks:
  services-network:

volumes:
  products-db:
    driver: local
  basket-redis-cache:
    driver: local
  seq-logs:
    driver: local
#HOW
# MENAGE STARTING PROFILES DEV/DEBUG/PROD
# STOP DOCKER COMPOSE CONTAINER ???
services:
  product-service:
    image: ${DOCKER_REGISTRY-}product-service
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV_PRODUCT_SERVICE}
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
    - "5000:80"
    - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
    - services-network
    depends_on:
    - product-db
    - seq

  product-db:
    container_name: products-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - products-db:/var/opt/mssql
    networks:
    - services-network 

  basket-service:
    image: ${DOCKER_REGISTRY-}basket-service
    build:
      context: .
      dockerfile: BasketService/Dockerfile
    container_name: basket-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV_BASKET_SERVICE}
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
    - "5002:80"
    - "5003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
    - services-network
    depends_on:
    - basket-redis

  seq:
    image: datalust/seq:latest
    container_name: seq
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 14G
    restart: unless-stopped
    ports:
    - "5341:80"
    volumes:
      - seq-logs:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
    - services-network

  basket-redis:
    container_name: basket-redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
    - basket-redis-cache:/data
    networks:
    - services-network
   #message-bus: rabbiitMQ




